### PR TITLE
Fixes #91: IPv6 does not accept lower case letters

### LINKED ISSUE #91: IPv6 does not accept lower case letters
Caught by @sdhiman99 .

IPv6 inputs do not seem to allow lower-case letters

### PR DESCRIPTION
**Pull request by sdhiman99**
Fixes #91 
IPv6 does not accept lower case letters
- I changed the regex to include lowercase IPv6 addresses. Is this ok, or should I change `updateIP({ v4, v6 }) ` method and do something like `this.checkIPv6(ip.toUpperCase())`?

### CODE REVIEW

**Comment by b-m-f** [comment]
Hey @sdhiman99 ,

Thanks for the work!

I think this should be fine, as IPv6 is not case-sensitive. Its just HEX decimal values.

**Review by b-m-f — APPROVED** [review]

**Comment by sdhiman99** [comment]
Thanks @b-m-f. 
Is there anything in the Interface part that I can contribute to, maybe a bit more complex issue.

**Comment by b-m-f** [comment]
@sdhiman99,

I will go through all the TODOs now and create some new issues.

If you want you can choose any that you are interested in.

**Comment by b-m-f** [comment]
@sdhiman99 ,

I have created the tickets.Some are pretty complex, such as the DNS or IPv6 subnet one.

Feel free to pick any one that you like though. If you need any more information from me on any of them just ask and Ill be glad to help :)

**Comment by sdhiman99** [comment]
Thanks @b-m-f, I'll go through the issues.

**Pull request merged**
